# Generated by Django 3.1.6 on 2021-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cnpj',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
