# Generated by Django 3.1.6 on 2021-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210210_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(default='05/29/2015 05:50:06', max_length=200),
            preserve_default=False,
        ),
    ]
